language: php

php:
  - 5.4
  - 5.5
  - hhvm
  - hhvm-nightly

env:
  - DOCTRINE_COMMON_VERSION="~2.2.0"
  - DOCTRINE_COMMON_VERSION="~2.3.0"
  - DOCTRINE_COMMON_VERSION="~2.4.0"
  - DOCTRINE_COMMON_VERSION="dev-master"

before_script:
  - sudo apt-get install -y postgresql-contrib
  - sudo /etc/init.d/postgresql reload
  - sudo -u postgres psql -c "create database orm_behaviors_test"
  - sudo -u postgres psql orm_behaviors_test -c "create extension cube"
  - sudo -u postgres psql orm_behaviors_test -c "create extension earthdistance"
  - composer require doctrine/common:${DOCTRINE_COMMON_VERSION}

script: bin/phpunit --testdox

